//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminECommerceModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        public int Id { get; set; }
        public string Address { get; set; }
        public string LandLine { get; set; }
        public string CellPhone { get; set; }
        public string Email { get; set; }
        public string Skype { get; set; }
        public string Facebook { get; set; }
        public string Gmail { get; set; }
        public string Twitter { get; set; }
        public string Instagram { get; set; }
        public string Working { get; set; }
        public string AccountID { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
