//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminECommerceModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Message1 { get; set; }
        public string AccountID { get; set; }
        public Nullable<bool> IsAnswered { get; set; }
        public string AnsweredAccountId { get; set; }
        public string Answer { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
