//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminECommerceModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.Banners = new HashSet<Banner>();
            this.OrderDetails = new HashSet<OrderDetail>();
            this.Promotions = new HashSet<Promotion>();
            this.Reviews = new HashSet<Review>();
            this.Accounts = new HashSet<Account>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int CategoryID { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Image3 { get; set; }
        public string Image4 { get; set; }
        public string Manufacturer { get; set; }
        public string Description { get; set; }
        public string ShortDescription { get; set; }
        public string OtherInfo { get; set; }
        public int Stock { get; set; }
        public System.DateTime DateArrivals { get; set; }
        public Nullable<double> SaleOff { get; set; }
        public string AttVal1 { get; set; }
        public string AttVal2 { get; set; }
        public string AttVal3 { get; set; }
        public string AttVal4 { get; set; }
        public string AttVal5 { get; set; }
        public string AttVal6 { get; set; }
        public string AttVal7 { get; set; }
        public string AttVal8 { get; set; }
        public string AttVal9 { get; set; }
        public string AttVal10 { get; set; }
        public Nullable<int> RatingScore { get; set; }
        public Nullable<int> NumOfRates { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Banner> Banners { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promotion> Promotions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Review> Reviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Account> Accounts { get; set; }
    }
}
