//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminECommerceModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Promotion
    {
        public string Id { get; set; }
        public double Discount { get; set; }
        public string Description { get; set; }
        public int Type { get; set; }
        public string ProductID { get; set; }
        public string AccountID { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
